[package]
name = "twincat"
version = "0.1.0"
edition = "2021"
description = "TwinCAT ADS tools"
keywords = ["Beckhoff", "TwinCAT", "ADS", "Structured-Text"]
license = "MIT"
readme = "readme.md"
repository = "https://github.com/becky112358/twincat"

[build-dependencies]
bindgen = "0.70.1"

[dependencies]
zerocopy = "0.7.35"
